### PR TITLE
add numpy to the dependencies + require python>=2.7 only

### PR DESCRIPTION
**Pull request by mwouts**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwouts** [comment]
Hey @asford , thank you for maintaining this project!

On the [last PR](https://github.com/conda-forge/itables-feedstock/pull/21) I noticed that the bot identified missing dependencies. I have prepared an update of the `itables` project at https://github.com/mwouts/itables/issues/149, but I think I will have to update the `meta.yaml` file as well.

I have the following questions for you
1. `requests` is only required at build time, and I see that it is already in the `host` requirements, maybe we cannot fix the bot message for that one?
2. `pytz` will be optional after https://github.com/mwouts/itables/issues/149, do you think that will be enough to remove it from the list of identified dependencies? How do we declare an optional dependency in `meta.yaml`?

**Comment by asford** [comment]
For sure, the direct source code inspection is a little flaky in cases like this. 
I've updated the automerge configuration to use grayskull, which uses the source's package configuration to track deps.
This *should* be a little better than the direct analysis, but I'm not sure.
As far as I know, it's not possible to silence the analysis false positives...

See #23 

Conda, because it relies on a strict SAT solver, doesn't have the concept of optional dependencies.
Things like build variants and/or optional deps need to be represented as separate installable targets,
which is ...a bit tricky to manage.

I'd recommend that you either (a) just leave `pytz` out of the dep list or (b) include it even through it's optional.
Both patterns are present in conda-forge, typically packages pull in their "lightweight" optional deps.
`pytz`, in particular, is pretty lightweight and is likely to be installed in many environments anyway.

**Review by asford — CHANGES_REQUESTED** [review]
Need to tick build number.
I'd push directly, but I don't have write access to your fork.

**Comment by mwouts** [comment]
Thank you so much @asford ! I have increased the build number, when the checks become green I will merge this, then I will release on `pip` the new version of `itables`. Thanks!

**Comment by asford** [comment]
My pleasure, thank you for the work on itables. 🙏

**Pull request merged**
